### ISSUE TITLE
bug in camera

### ISSUE THREAD

**Issue by marcomusy** [K3D-tools/K3D-jupyter#180]
It seems that camera is not updated when viewup is modified but camera position is not changed:
```python
import k3d
import numpy as np
from numpy import sin,cos,pi
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import time
import math

plot = k3d.plot()

plot.camera_auto_fit = False

T = 1.618033988749895
r = 4.77
zmin,zmax = -r,r
xmin,xmax = -r,r
ymin,ymax = -r,r
Nx,Ny,Nz = 77,77,77

x = np.linspace(xmin,xmax,Nx)
y = np.linspace(ymin,ymax,Ny)
z = np.linspace(zmin,zmax,Nz)
x,y,z = np.meshgrid(x,y,z,indexing='ij')
p = 2 - (cos(x + T*y) + cos(x - T*y) + cos(y + T*z) + cos(y - T*z) + cos(z - T*x) + cos(z + T*x))
iso = k3d.marching_cubes(p.astype(np.float32),xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax, zmin=zmin, zmax=zmax, level=0.0)
plot += iso

plot.display()
```
this doesnt work:
```python
@interact(rad=widgets.FloatSlider(value=0,min=0,max=1,step=0.01))
def g(rad):
    plot.camera = [8,0,8,
                   0,0,0,
                   0,1-rad,rad]
```

while this works:
```python
@interact(rad=widgets.FloatSlider(value=0,min=0,max=1,step=0.01))
def g(rad):
    plot.camera = [8,0,8+rad/100,
                   0,0,0,
                   0,1-rad,rad]
```

**Comment by artur-trzesiok** [comment]
Nice spot! This is a issue in ThreeJs: https://github.com/mrdoob/three.js/blob/master/examples/js/controls/TrackballControls.js#L357

ThreeJs emite change event only if position change. They ignore a up vector. You can add them a issue.

**Comment by artur-trzesiok** [comment]
@marcomusy can you confirm that in 2.7.0 this issue is already fixed?

**Comment by marcomusy** [comment]
Hi @artur-trzesiok sorry for the late reply - this slipped off my mind - I just tried it again with the above example and I still get the same weird behavior in k3d 2.7.

**Comment by artur-trzesiok** [comment]
Can you double check version of js part of k3d?
![image](https://user-images.githubusercontent.com/5256837/68121985-991b4300-ff09-11e9-96a9-ad21ca9cf029.png)

**Comment by marcomusy** [comment]
oh yes - that shows 2.6.9
what should i do to trigger the update?

**Comment by marcinofulus** [comment]
If you use conda package and the same env for both notebook then it should work. You might want to restart notebook. In other cases it might be necessary to use:
 - `jupyter nbextension install --sys-prefix --py k3d`
 - `jupyter nbextension enable --sys-prefix --py k3d`

**Comment by marcomusy** [comment]
Hi @marcinofulus I tried but still get the 2.6.9 js version..
I also tried restarting the browser.. any ideas?

![image](https://user-images.githubusercontent.com/32848391/68125147-28782480-ff11-11e9-8179-a013419e2f2a.png)

**Comment by marcinofulus** [comment]
check for `jupyter --paths`: - perhaps you have k3d installed in to localtion e.g in system and user space. Also have a look at `jupyter nbextension list`. It is possible that you will have to delete some location if there are doubled.

In principle, if jupyter notebook is running kernel from some different env - then I use --user for nbextensions (like central jupyterhub installations)
