### ISSUE TITLE
k3d plot does not show in jupyter notebook even though code runs fine

### ISSUE THREAD

**Issue by wjcramer** [K3D-tools/K3D-jupyter#380]
Hi,

I followed the install instructions, I ran:

```
$ pip install k3d
$ pip install jupyter_contrib_nbextensions  
$ jupyter nbextension install --py --user k3d
$ jupyter nbextension enable --py --user k3d
```

I see the relevant nbextensions as being installed in jupyter:

<img width="1146" alt="Screen Shot 2022-10-03 at 10 10 23 PM" src="https://user-images.githubusercontent.com/87668901/193739291-ab3b9510-241f-4c08-a528-55c016290464.png">

But when I run my code:

```
import numpy as np
from astropy.io import fits

import k3d
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets

[...]

plt_volume = k3d.volume(masked_cube, alpha_coef=125,
                        color_range=[0.002, 0.01])

plot = k3d.plot()
plot += plt_volume
plot.display(vmin=0.005, vmax=0.2)
```

It executes with no errors or crashes, but no display, plot, or widget window comes up. I also tried installing through the conda environment and had the same issue. I am running on a Mac OS Catalina in a chrome browser window with the latest version of python (3.9.13). I have the same issue trying to run any of the example scripts.

**Comment by renefritze** [comment]
You're most probably hit with https://github.com/K3D-tools/K3D-jupyter/issues/371 which should be fixed after #378 is merged and a new tag released.

**Comment by wjcramer** [comment]
#371 seems to suggest that downgrading:

`pip uninstall jupyterlab-widgets ipywidgets
pip install ipywidgets==7.7.1 jupyterlab-widgets==1.1`

fixes the problem, unfortunately doesn't seem to do the trick for me.

**Comment by tennysontbardwell** [comment]
FYI: downgrading ipywidgest and jupyterlab-widgets is currently breaking matplotlib interactive widgets for me.

**Comment by mli0603** [comment]
I tried the following:

```
pip install git+https://github.com/agoose77/K3D-jupyter#chore-use-hatch --force-reinstall
pip install ipywidgets==7.7.1 jupyterlab-widgets==1.1 --force-reinstall
```

But still seeing this error

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'PlotModel' from module 'k3d'
Error: No version of module k3d is registered
    at f.loadClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:74856)
    at f.loadModelClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:10729)
    at f._make_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:7517)
    at f.new_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:5137)
    at f.handle_comm_open (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:3894)
    at _handleCommOpen (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:73393)
    at b._handleCommOpen (http://localhost:8888/static/lab/jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:996724)
    at async b._handleMessage (http://localhost:8888/static/lab/jlab_core.716b79be8019e5bdc801.js?v=716b79be8019e5bdc801:2:998714)
```

**Comment by renefritze** [comment]
Even with @agoose77's PR branch there's still [this problem](https://github.com/K3D-tools/K3D-jupyter/pull/378#issuecomment-1268189441) which also happens on main, but is unrelated to the changes needed to be compatible with current ipywidgets.

**Comment by artur-trzesiok** [comment]
Please try 2.15.0 (https://pypi.org/project/k3d/ for conda-forge we need to wait a little bit). @renefritze contribution should solve that

**Comment by wjcramer** [comment]
I tried the same code as posted at the top running the new 2.15.0 version, it has not solved the issue of no graphical interface appearing after I run the code.

**Comment by artur-trzesiok** [comment]
@wjcramer Sorry for that. Can you double check if that is not a browser cache? Can you ran your code in incognito mode or after deleting browser cache?

**Comment by glmourad** [comment]
Same for me using 2.15.0

![image](https://user-images.githubusercontent.com/532369/220700785-4bb28970-b7f6-43c2-ab81-9ec82244a406.png)

**Comment by artur-trzesiok** [comment]
@glmourad do you use VS Code or web interface?
