### ISSUE TITLE
Improve handling of context loss

### ISSUE THREAD

**Issue by martinal** [K3D-tools/K3D-jupyter#50]
While creating lots of test plots in a notebook, I notice that the initial plots behaves strangely. The plot contents and grid is gone, but the numbers and letters on the xyz axes are still there and interaction works. I'm not sure exactly what's needed to reproduce yet, but I'm guessing it's related to webgl context loss.

**Comment by martinal** [comment]
Doing a detach fixes the plot, and after reattach the plot is fine in the notebook too.

**Comment by martinal** [comment]
There's a (huge) branch of pythreejs which contains (besides basically a full rewrite) an approach to dealing with context loss, see this code:

https://github.com/jovyan/pythreejs/pull/88/commits/738f719e5f021b0de992cf082abd1eab20ed47a7#diff-2f0672887a2753687848ddc32e14306a

**Comment by artur-trzesiok** [comment]
It's very probably that in the latest version problem is solved. @martinal could you try to reproduce the issue ?

**Comment by martinal** [comment]
Issue is still there. To reproduce, create a new notebook, first cell:
```
import k3d
```
then N cells just displaying a plot each (for me N=17 triggered context loss):
```
k3d.plot()
```
Then when the browser console shows
```
WARNING: Too many active WebGL contexts. Oldest context will be lost.
```
scroll up to the top and the first plot looks like the attached picture.
![k3d-context-loss](https://user-images.githubusercontent.com/378115/27335604-6125827c-55cd-11e7-8ea5-6d951592492f.png)

**Comment by vidartf** [comment]
The pythreeJS solution to this is to keep N canvases around for rendering. Anything that tries to render requests one of these together with a callback when it has to give it up. When it has to give it up, it replaces the canvas element with a PNG image of the last drawn frame.

Links to the latest code:
 - The canvas manager is here: https://github.com/vidartf/pythreejs/blob/8c38c276bc4822e2f1dbb921ffd1ebc0b0a40d64/js/src/_base/RendererPool.js
 - The code line to replace the current canvas with an image is here: https://github.com/vidartf/pythreejs/blob/23cad6ebdf297c4a58b888d54674b040814eb97d/js/src/_base/Renderable.js#L165
